PUB-1803 Clean up PDFs
hmcts/pip-channel-management pull request #125
Opened 2023-02-07 13:28 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1803

### Change description ###

- Updated all PDFs to use arial over GDS Transport
- Removed gov crest from PDFs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-09 10:35 UTC, KianKwa approved these changes

2023-02-13 17:03 UTC, junaidiqbalmoj approved these changes

2023-02-14 09:19 UTC, ChrisS1512 requested changes

2023-02-14 09:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            File file = new File("/opt/app/arial.ttf");
Marking this as Changes Requested while discussion ongoing on whether arial font is OK to use

2023-02-14 16:03 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            File file = new File("/opt/app/arial.ttf");
Updated and agreed as discussed

2023-02-23 10:35 UTC, ChrisS1512 approved these changes

2023-02-23 10:38 UTC, merged