PUB-1808 Check user is authorised
hmcts/pip-channel-management pull request #130
Opened 2023-02-14 13:27 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1808

### Change description ###

Added check to ensure user is authorised to access the stored publication files being requested. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-15 17:45 UTC, KianKwa approved these changes

2023-02-16 14:17 UTC, ChrisS1512 requested changes

2023-02-16 14:17 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/exceptions/AuthorisedException.java
> +public class AuthorisedException extends RuntimeException {
I think this should be UnauthorisedException instead just to be clear.

2023-02-16 15:25 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/errorhandling/exceptions/AuthorisedException.java
> +public class AuthorisedException extends RuntimeException {
Done

2023-02-17 10:38 UTC, furnivall approved these changes

2023-02-28 14:12 UTC, ChrisS1512 approved these changes

2023-02-28 14:12 UTC, merged