PUB-1895 Update Open Justice Statement
hmcts/pip-channel-management pull request #146
Opened 2023-03-01 17:26 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1895

### Change description ###

Update Open Justice Statement for the following lists:

Care Standards list
Civil and Family Daily Cause list
Civil Daily Cause list
COP Daily Cause list
Family Daily Cause list
SSCS Daily list
SSCS Daily list - additional hearings

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-03 15:44 UTC, ChrisS1512 requested changes

2023-03-03 15:44 UTC, ChrisS1512 commented on src/main/resources/templates/sscsDailyList.html
> +    <p th:text="${i18n.importantInformationP2a + metadata.locationName + i18n.importantInformationP2b  + email
Similar here with email and telephone, but other than that looks good :)

2023-03-07 17:23 UTC, ChrisS1512 approved these changes

2023-03-07 17:32 UTC, furnivall approved these changes

2023-03-15 10:40 UTC, merged