PUB-1737 Remove code smell and improve test coverage
hmcts/pip-channel-management pull request #150
Opened 2023-03-16 11:46 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1737

### Change description ###

Remove code smell and improve test coverage

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-16 16:40 UTC, ChrisS1512 requested changes

2023-03-16 16:40 UTC, ChrisS1512 commented on src/test/resources/mocks/magistratesStandardList.json
> +                      },
I'd change some of the below (Forenames, Offence wording) to Test etc instead, just to make it clear it is just a test file

2023-03-17 14:04 UTC, ChrisS1512 approved these changes

2023-03-17 14:48 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/listmanipulation/MagistratesStandardListHelperTest.java
>                       "Unable to hearing channel");
from here onwards, needs a verb for similar lines

2023-03-17 15:43 UTC, furnivall approved these changes

2023-03-22 11:00 UTC, merged