Pub 1010 the birth of channel management
hmcts/pip-channel-management pull request #16
Opened 2022-05-18 16:43 UTC by furnivall

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1010

### Change description ###
- Establishes linkages between subscription management -> channel management -> account management and back to subscription management.
- Deduplicates subscriptions where a single user is subscribed to the same object via multiple means (e.g. both CASE_ID and CASE_URN)
- Takes in a list of subscriptions from subscription management and returns a map of email addresses to subscription objects associated with that user.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-23 08:43 UTC, kurt-uk requested changes

2022-05-23 08:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/demo/controllers/SubscriptionManagementController.java
> +        });
⬆️  👍🏼

2022-05-23 08:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/demo/models/Channel.java
> +package uk.gov.hmcts.reform.demo.models;
try keep the models not native to this service separate so its not confused as part of channel management

2022-05-23 08:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/demo/services/AccountManagementService.java
> +            return  webClient.post().uri(new URI(String.format(
no URI contructor methods are used here you can just yeet out new uri if you dont test it in your catch clause

2022-05-23 08:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/demo/services/AccountManagementService.java
> +            return  webClient.post().uri(new URI(String.format(
or if you do wanna keep it, make sure you unit test the scenario that catch clause is met

2022-05-23 08:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/demo/controllers/SubscriptionManagementController.java
> +            subscriptionManagementService.deduplicateSubscriptions(listOfSubscriptions);
why is this handled as part of an instant back forth? sub man has just sent channel man this list right? why would it be instantly be sent back to deduplicate? this call doesnt make much sense, seems like it should be handlded at the point of sending

2022-05-23 08:43 UTC, kurt-uk commented on src/main/resources/application.yaml
> +service-to-service:
auth for cross service calls looks like it might need to be added too

2022-05-23 08:43 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/rsecheck/controllers/SubscriptionManagementControllerTest.java
> +        List<Subscription> subscriptionList = new ArrayList<>();
these dont need to be this big, (its due to over complex controllers, will be reduced when service logic is extracted from controller)

2022-05-23 08:43 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/AccountManagementServiceTest.java
> +        mockAccountManagementGetEmailsEndpoint.shutdown();
can probably be added to an afterEach()

2022-05-23 08:43 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/SubscriptionManagementServiceTest.java
> +            subscriptionManagementService.deduplicateSubscriptions(subscriptionList);
where are your mocks for this class?

2022-05-23 08:43 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/SubscriptionManagementServiceTest.java
> +}
also you have no catch tests

2022-05-23 09:00 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/AccountManagementServiceTest.java
> +        mockAccountManagementGetEmailsEndpoint.shutdown();
good shout

2022-05-23 09:31 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/config/WebClientConfig.java
> +    }
Cheers - have now implemented this.

2022-05-23 09:32 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/config/WebClientConfig.java
> +@EnableAsync
removed

2022-05-23 09:37 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/controllers/SubscriptionManagementController.java
> +public class SubscriptionManagementController {
Yeah, sorry, I initially was thinking of having both a subs man and account man controller but then realised i was being silly and never renamed. Fixed now :)

2022-05-23 09:53 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/config/WebClientConfig.java
> +package uk.gov.hmcts.reform.demo.config;
pahaha. this one made me giggle. i have now fixed it.

2022-05-23 09:56 UTC, furnivall commented on src/main/resources/application.yaml
> +service-to-service:
sorted as confirmed with you in slack

2022-05-23 10:18 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/SubscriptionManagementServiceTest.java
> +}
No try block either!

2022-05-23 12:30 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/controllers/SubscriptionManagementController.java
> +        });
Have now done this - sorry it wasn't clean when i initially pushed, was trying to get things done quickly before holiday!

2022-05-23 12:30 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/config/WebClientConfig.java
> +@EnableAsync
yep, removed

2022-05-23 12:35 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/controllers/SubscriptionManagementController.java
> +@Api(tags = "Account management API")
Added a bit more to the tag and changed it :)

2022-05-23 12:37 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/demo/models/Channel.java
> +package uk.gov.hmcts.reform.demo.models;
Have moved into models/external.subscriptionmanagement :)

2022-05-23 12:39 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/rsecheck/controllers/SubscriptionManagementControllerTest.java
> +        List<Subscription> subscriptionList = new ArrayList<>();
Yeah, have massively cut these down now :)

2022-05-23 12:39 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/rsecheck/services/AccountManagementServiceTest.java
> +        mockAccountManagementGetEmailsEndpoint.shutdown();
yeah, added the setup and teardown methods

2022-05-23 14:07 UTC, kurt-uk requested changes

2022-05-23 14:07 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/DuplicationAndEmptyHandlerService.java
> +public class DuplicationAndEmptyHandlerService {
dont forget java docs to explain methods like these

2022-05-23 14:07 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/DuplicationAndEmptyHandlerService.java
> +    public Map<String, List<Subscription>> mapCleaner(Map<String, List<Subscription>> userIdMap, Map<String,
not sure `mapCleaner` is a good name, try to give descriptive method names

2022-05-23 14:09 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/controllers/ChannelManagementController.java
> +        if (mapOfUsersAndEmails.isEmpty()) {
They're logged in the service layer.

2022-05-23 15:34 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/AccountManagementService.java
> +
done

2022-05-23 15:34 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/controllers/ChannelManagementController.java
> +                                                                                                  mapOfUsersAndEmails);
done as far as possible without changing back to subs man

2022-05-23 15:34 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/DuplicationAndEmptyHandlerService.java
> +    public Map<String, List<Subscription>> mapCleaner(Map<String, List<Subscription>> userIdMap, Map<String,
renamed now

2022-05-23 15:53 UTC, ChrisS1512 requested changes

2022-05-23 15:53 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/channel/management/controllers/ChannelManagementController.java
> +@Api(tags = "Channel management API - middle endpoint for subscription-management -> account-management requests.")
I woul;d remove the middle endpoint bit on here, and change the description to describe what channel management is doing. This prevents the coupling between the services

2022-05-23 15:54 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/controllers/ChannelManagementController.java
> +@RequestMapping("/account")
I'm easy with anything but will need Josh to change his end too I guess?

2022-05-23 16:14 UTC, kurt-uk requested changes

2022-05-23 16:14 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/BuildSubscriberListService.java
> +public class BuildSubscriberListService {
this is a method name, a class name would the name of a service, not an action its performing

2022-05-23 16:14 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/BuildSubscriberListService.java
> +    public Map<String, List<Subscription>> finalSubscriptionEmailMapHandler(Map<String, List<Subscription>> userIdMap,
does this need to be public?

2022-05-23 16:35 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/BuildSubscriberListService.java
> +public class BuildSubscriberListService {
![image](https://user-images.githubusercontent.com/18507008/169866434-30ea5081-f615-42c6-b7d7-da6b3ae30803.png)

I mean I'll take this kind of thing basically indefinitely from you because I want to learn but you have to at least admit that your messages are somewhat mixed here

2022-05-23 16:53 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/BuildSubscriberListService.java
> +    public Map<String, List<Subscription>> finalSubscriptionEmailMapHandler(Map<String, List<Subscription>> userIdMap,
Fixed as with the one above

2022-05-23 17:04 UTC, furnivall commented on src/integrationTest/java/uk/gov/hmcts/reform/channel/management/controllers/GetWelcomeTest.java
> +package uk.gov.hmcts.reform.channel.management.controllers;
don

2022-05-23 17:05 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/services/DuplicationAndEmptyHandlerService.java
> +    public Map<String, List<Subscription>> mapCleaner(Map<String, List<Subscription>> userIdMap, Map<String,
done

2022-05-23 17:05 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/channel/management/controllers/ChannelManagementController.java
> +@Api(tags = "Channel management API - middle endpoint for subscription-management -> account-management requests.")
Done

2022-05-23 17:36 UTC, ChrisS1512 approved these changes

2022-05-25 09:54 UTC, kurt-uk approved these changes

2022-06-01 09:36 UTC, merged