Pub 1999
hmcts/pip-channel-management pull request #184
Opened 2023-05-16 14:19 UTC by NatashaAlker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1999

### Change description ###

Display "ListAssist" rather than "SNL" as the Data Source when generating PDFs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-23 14:20 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +    private static final String UPDATED_LA_REF = "LIST_ASSIST";
Just checked the ticket and it says it should be updated to ListAssist not LIST_ASSIST, just wondering if requirements have changed since or if ListAssist is still valid?

2023-05-23 14:35 UTC, ChrisS1512 requested changes

2023-05-23 14:35 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        String provenance = OUTDATED_LA_REF.equals(artefact.getProvenance())
Would you be able to add a unit test for this bit here to check the if statement logic?

2023-05-25 16:18 UTC, ChrisS1512 approved these changes

2023-05-26 08:07 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        return "SNL".equals(provenance) ? "ListAssist" : provenance;
There are 2 paths here, i.e. provenance equals "SNL" or not equals "SNL". It is better to have 2 unit tests testing both paths for sonarCloud code coverage

2023-05-31 12:37 UTC, merged