added third party api value builder to add to subscriptions
hmcts/pip-channel-management pull request #19
Opened 2022-06-08 17:22 UTC by kurt-uk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-949

### Change description ###
added  api values for third party, changed channel model to hold the correct API_COURTEL value

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-10 10:48 UTC, joshblackmoor approved these changes

2022-06-13 13:57 UTC, ChrisS1512 requested changes

2022-06-13 13:57 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
> +                throw new ChannelNotFoundException("Invalid channel for API subscriptions: "
Just wondering if rather than throwing an exception here, we should skip this loop or maybe put the subscription list against a null key instead?

This will mean the matched ones could still progress without blocking them all

2022-06-14 10:43 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/SubscriberListService.java
> +                throw new ChannelNotFoundException("Invalid channel for API subscriptions: "
this would be failing for all of them though, the subscribers object are all of the same channel type and the channel is determined by first item, so if the list was sent with the wrong payload subscriptions it would need to be handled

2022-06-14 12:53 UTC, ChrisS1512 approved these changes

2022-06-20 11:10 UTC, merged