Pub 2054 - Add SJP delta press list
hmcts/pip-channel-management pull request #222
Opened 2023-07-21 07:49 UTC by NatashaAlker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2054

### Change description ###

Add SJP delta press list (new cases)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-24 09:55 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
>              } else {
The SJP press list language resource files need to be updated with the new title for the PDF. A new language resource file for the SJP press delta list should also be added to override the title.

2023-07-24 09:58 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverterTest.java
>          }
Need to add a new test for SjpPressListFileConverter too

2023-07-25 13:21 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
>              } else {
This has been done

2023-07-25 13:21 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryConverterTest.java
>          }
New test added

2023-07-26 17:09 UTC, ChrisS1512 requested changes

2023-07-26 17:09 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
>       * @return The converted Excel spreadsheet as a byte array.
list type needs adding to the java doc above

(Similar comment for other changes)

2023-07-27 08:20 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
>       * @return The converted Excel spreadsheet as a byte array.
Now updated

2023-07-27 14:57 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/SjpPressListFileConverter.java
>       * @return The converted Excel spreadsheet as a byte array.
This time the javadoc is updated with the new param for SJP public and SJP press file converter

2023-07-27 15:24 UTC, ChrisS1512 approved these changes

2023-07-27 15:41 UTC, junaidiqbalmoj approved these changes

2023-08-02 09:37 UTC, merged