PUB-1711 Generate additional Welsh PDF for gov.uk Notify
hmcts/pip-channel-management pull request #248
Opened 2023-08-22 14:36 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1711

### Change description ###

Generate additional Welsh PDF for gov.uk Notify

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-25 14:40 UTC, ChrisS1512 requested changes

2023-08-25 15:52 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        Triple<byte[], byte[], byte[]> files = publicationFileGenerationService.generate(artefactId);
I have made a new model class called PublicationFiles to contain those files :)

2023-08-25 15:59 UTC, ChrisS1512 approved these changes

2023-08-31 13:29 UTC, KianKwa commented on src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
> +        verify(azureBlobService).deleteBlobFile(ARTEFACT_ID_SJP_PUBLIC_LIST_DELETE + PDF.getExtension());
Think that should be a second verify here to verify the Excel is also being deleted for SJP:
Verify(azureBlobService).deleteBlobFile(ARTEFACT_ID_SJP_PUBLIC_LIST_DELETE + EXCEL.getExtension());

2023-08-31 13:32 UTC, KianKwa commented on src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
> +        verify(azureBlobService)
I assume this is a Welsh publication? If so we also need the second verify to prove that the additional PDF is getting deleted but not excel is deleted:
Verify(azureBlobService).deleteBlobFile(ARTEFACT_ID_SJP_PUBLIC_LIST_DELETE + "_cy" + PDF.getExtension());
Verify(azureBlobService, never()).deleteBlobFile(ARTEFACT_ID_SJP_PUBLIC_LIST_DELETE + EXCEL.getExtension());

2023-08-31 13:34 UTC, KianKwa commented on src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
> +    void testDeleteFilesSuccess() throws Exception {
Since we are using "verify" to check the logic of file deletion, worth adding a English publication for mixed list and show no additional PDF is getting deleted

2023-09-08 11:13 UTC, merged