Pub 1977 - Add OPA Public List
hmcts/pip-channel-management pull request #284
Opened 2023-12-04 17:15 UTC by NatashaAlker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1977

### Change description ###

Add pdf generation for OPA Public List

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-12-07 12:21 UTC, KianKwa commented on src/main/resources/templates/languages/en/opaPublicList.json
> +  "listDetail": "List containing CASES_COUNT case(s) generated on",
Think we are supposed to show the number of cases like the frontend one but I can't see this line here used anywhere in the HTML

2023-12-07 12:55 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/OpaPublicListHelper.java
> +        return new OpaCaseInfo(
Hhhmmm not keen of re-using the model class from opapresslist because the package name saying it is for OPA press list only. You can do either one of the following:
- Rename the folder of the model class to "opalists" then combine all OPA Public List and OPA Press List models into the same folders. You could reuse most of the models from OPA press list (except the main one) as the press list models are supreset of the public list. You will need to modify the existing press list code as the name of the package will change.
- Add OpaCaseInfo into the opapubliclist folder too so press list and public list models are independent.

2023-12-07 12:59 UTC, KianKwa commented on src/main/resources/templates/opaPublicList.html
> +            <td th:each="offence : ${row.defendant.offences}" th:text="${offence.offenceTitle + ' - ' + offence.offenceSection + ' Reporting Restriction - ' + offence.offenceReportingRestriction}"></
According to the ticket, there should be an empty lines between offence info and reporting restriction part

2023-12-21 17:38 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/OpaPublicListHelper.java
> +    private static final String DATE_FORMAT = "dd/MM/yyyy";
The date format for scheduled first hearing is different to the one in frontend. They should be consistent

2023-12-22 09:23 UTC, ChrisS1512 requested changes

2023-12-22 09:23 UTC, ChrisS1512 commented on config/owasp/suppressions.xml
> +  <suppress>
I don't believe these new suppressions are needed (I've just tried it locally and seems OK without). 

Could you try removing the new ones below and adding the above removed one back in?

2024-01-09 13:17 UTC, merged