PUB-2288 Create V2 version of delete publication files endpoint
hmcts/pip-channel-management pull request #299
Opened 2024-01-12 14:56 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2288

### Change description ###

Create V2 version of delete publication files endpoint

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-01-15 12:11 UTC, ChrisS1512 requested changes

2024-01-15 12:11 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementController.java
> +    @ApiResponse(responseCode = NO_CONTENT_CODE, description = "The files have been deleted")
Can you mark the other endpoint as Deprecated

2024-01-16 09:38 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementController.java
> +    @ApiResponse(responseCode = NO_CONTENT_CODE, description = "The files have been deleted")
Have marked the old endpoint as deprecated

2024-01-16 09:38 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +    public void deleteFiles(UUID artefactId, ListType listType, Language language) {
Fixed :)

2024-01-17 17:09 UTC, ChrisS1512 approved these changes

2024-01-22 13:46 UTC, merged