Pub 2290 Crime lists - Move party to case level
hmcts/pip-channel-management pull request #309
Opened 2024-02-06 16:58 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2290

### Change description ###

Crime lists - Move party to case level

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-13 16:15 UTC, ChrisS1512 requested changes

2024-02-13 16:15 UTC, ChrisS1512 commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/hearingparty/CrownFirmListSummaryConverterTest.java
> +    void testCrownDailyListTemplate() throws IOException {
Daily list title here needs updating

2024-02-13 17:41 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/hearingparty/CrownFirmListSummaryConverterTest.java
> +    void testCrownDailyListTemplate() throws IOException {
Test method name updated

2024-02-14 08:23 UTC, ChrisS1512 approved these changes

2024-02-19 10:55 UTC, merged