PUB-2190: Added 'caseType' field to Civil Daily Cause list
hmcts/pip-channel-management pull request #330
Opened 2024-03-21 11:23 UTC by alexbottenberg

https://tools.hmcts.net/jira/browse/PUB-2190

Added 'caseType' field to Civil Daily Cause list

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-21 14:38 UTC, MindGames2015 approved these changes

2024-03-21 14:53 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CivilDailyCauseListSummaryConverter.java
> +            String caseType = currentHearing.get("case").get(0).get("caseType").asText();
CaseType is not a mandatory field. So we will need to check whether it is present or not before retrieving the value, or else it will cause a null pointer exception if missing. It is better to use GeneralHelper.findAndReturnNodeText() so it can be avoided

2024-03-21 15:08 UTC, KianKwa requested changes
Please double check whether PDF has the case type column populated or not

2024-03-21 15:16 UTC, KianKwa commented on src/main/resources/templates/civilDailyCauseList.html
> +                    <td class="govuk-table__cell" th:text="${case.get('caseType').asText()}"/>
Hey Alex, I think this is fine. 'caseType' does not need to be pe-processed so it is reading it straight from the input JSON. No issue here so it should be populating it

2024-03-22 11:40 UTC, KianKwa commented on src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
> +        assertTrue(responseContent.contains("Case Type: type"), CONTENT_MISMATCH_ERROR);
The case type needs to be tested in testGenerateArtefactSummaryCivilAndFamilyDailyCauseList() too

2024-04-02 09:31 UTC, KianKwa approved these changes

2024-04-02 09:43 UTC, merged