PUB-2306 Family and mixed lists - Move party to case level
hmcts/pip-channel-management pull request #331
Opened 2024-03-21 16:39 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2306

### Change description ###

Family and mixed lists - Move party to case level

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-25 11:56 UTC, ChrisS1512 requested changes

2024-03-25 11:56 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CftListHelper.java
> +                FamilyMixedListHelper.manipulatedlistDataV1(artefact, language);
Similar comment to the frontend PR regarding method names

2024-03-25 17:55 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CftListHelper.java
> +                FamilyMixedListHelper.manipulatedlistDataV1(artefact, language);
Renamed to manipulatedListDataPartyAtHearingLevel()

2024-03-26 14:34 UTC, ChrisS1512 approved these changes

2024-04-02 17:39 UTC, merged