PUB-2186 - Modified IAC Lists and Tests
hmcts/pip-channel-management pull request #332
Opened 2024-03-22 15:19 UTC by MindGames2015

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/PUB-2186

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-25 09:27 UTC, ChrisS1512 requested changes

2024-03-25 09:27 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverter.java
> -        context.setVariable("telephone", artefact.get("venue").get("venueContact").get("venueTelephone").asText());
This now need to be replaced with the static values. The PDF is currently showing as null, null:

![image](https://github.com/hmcts/pip-channel-management/assets/87066931/11136edc-1b43-4f50-9885-d29181be65e7)

2024-03-25 09:27 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverter.java
>                                                                      hearingCase, "claimant");
Can you confirm with service whether we should add hearingType to the summary too?

2024-03-25 11:08 UTC, ChrisS1512 requested changes

2024-03-25 11:08 UTC, ChrisS1512 commented on src/test/resources/mocks/iacDailyList.json
> +      "courtListName": "",
I think we need to check with List Assist how these courtListNames are going to be coming over. If they come over as blank when non float list then this will work, otherwise this will need a change.

2024-03-27 10:08 UTC, MindGames2015 commented on src/test/resources/mocks/iacDailyList.json
> +      "courtListName": "",
Hi Chris, had a 3 Amigos with Sam, Hamza, Kian and Ogechi. The removal of the 'Bail List' header, is fine no other input from an external source is needed for this list.

2024-04-04 12:37 UTC, ChrisS1512 requested changes

2024-04-04 12:37 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverter.java
> -                                GeneralHelper.appendToStringBuilder(output, "List Name - ",
I think this line needs to be reverted back for now, while we await the outcome of the bail / float list discussion

2024-04-04 12:37 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverter.java
> +                                                           hearing.get("case").forEach(hearingCase -> {
Lots of indentation here. I think this needs moving back

2024-04-04 12:59 UTC, MindGames2015 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverter.java
>                                                                      hearingCase, "claimant");
I forgot too mention this change Chris, sorry.

2024-04-04 13:00 UTC, MindGames2015 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverter.java
> -        context.setVariable("telephone", artefact.get("venue").get("venueContact").get("venueTelephone").asText());
This is fixed Chris now. Thanks Chris.

2024-04-05 09:39 UTC, MindGames2015 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverter.java
> +                                                           hearing.get("case").forEach(hearingCase -> {
Moved line back to original place. Thanks Chris.

2024-04-05 09:40 UTC, MindGames2015 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverter.java
> -                                GeneralHelper.appendToStringBuilder(output, "List Name - ",
Reverted line back to original place. Thanks Chris.

2024-04-05 10:20 UTC, ChrisS1512 requested changes

2024-04-05 10:20 UTC, ChrisS1512 commented on src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/IacDailyListFileConverterTest.java
> -        softly.assertThat(doc.getElementsByTag("h1").get(0))
This assertion should be re-added back in too

2024-04-05 10:54 UTC, ChrisS1512 approved these changes

2024-04-23 16:04 UTC, ChrisS1512 approved these changes

2024-04-26 08:00 UTC, merged