PUB-2430 Update subscription email summary for all list types
hmcts/pip-channel-management pull request #361
Opened 2024-06-21 09:43 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2430

### Change description ###

Update subscription email summary for all list types

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-06-25 14:51 UTC, ChrisS1512 requested changes

2024-06-25 14:51 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CopDailyCauseListSummaryData.java
> +                                    GeneralHelper.findAndReturnNodeText(hearingCase, "caseSuppressionName"),
Case suppression name is not on the screenshot on the ticket. Is this correct?

2024-06-25 14:51 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownWarnedListSummaryData.java
> +                    "Hearing date", row.getHearingDate()
This is hearing type in the screenshots rather than date

2024-06-25 14:51 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/FamilyMixedDailyCauseListSummaryData.java
> +                                    Map<String, String> fields = ImmutableMap.of(
This is different than the screenshot on the ticket, although screenshot is potentially incorrect as it has defendant / prosecutor

2024-06-25 14:51 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryData.java
> +                            "Offence", offenceTitles
This is 'offence title' in the screenshot. Similar issue with a few lists.

2024-06-25 14:51 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SscsDailyListSummaryData.java
> +                "Appeal reference", hearingCase.getAppealRef()
Appeal reference is not in screenshot

2024-06-25 15:04 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CopDailyCauseListSummaryData.java
> +                                    GeneralHelper.findAndReturnNodeText(hearingCase, "caseSuppressionName"),
caseSuppressionName is the Case Details column on the frontend/PDF. Don't look at those screenshots Ogechi attached in the ticket. Those are not updated. Use the Email Summary Mock Up powerpoint file. I have discussed with Ogechi and that is the latest one to use.

2024-06-25 15:05 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownWarnedListSummaryData.java
> +                    "Hearing date", row.getHearingDate()
Hearing date is correct. I have flagged this up with Ogechi and he has updated the powerpoint file.

2024-06-25 15:07 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/FamilyMixedDailyCauseListSummaryData.java
> +                                    Map<String, String> fields = ImmutableMap.of(
The screenshots are wrong, use the powerpoint

2024-06-25 15:09 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryData.java
> +                            "Offence", offenceTitles
I have asked Ogechi to change Offence title to Offence. There is no more offence wording/section in all the list types. So offence title is just offence. She has updated the powerpoint only

2024-06-26 09:17 UTC, ChrisS1512 requested changes
The casing in the power point is upper case on each word, however the code is only upper case on the first word. Is this expected?

2024-06-26 09:17 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPressListSummaryData.java
> +            "Name", accused.get(),
This is 'Defendant' in the powerpoint

2024-06-26 09:17 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/SjpPublicListSummaryData.java
> +                                    "Name", sjpCase.getName(),
Same here regarding Defendant in power point

2024-06-26 09:28 UTC, ChrisS1512 approved these changes

2024-07-05 07:54 UTC, merged