Added PDF/Excel code to service
hmcts/pip-channel-management pull request #40
Opened 2022-10-17 12:39 UTC by joshblackmoor

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-24 18:45 UTC, joshblackmoor commented
Requires https://github.com/hmcts/pip-shared-infrastructures/pull/75 to be merged for the build to pass.

2022-10-25 15:20 UTC, KianKwa commented on src/main/resources/templates/testTemplate.html
> +<!DOCTYPE html>
Dont think this file is needed anymore. It was probably used for Danny's original PDF prototyping. Please check and removed if not used anymore.

2022-10-25 15:23 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/templatemodels/SjpPressCase.java
> +package uk.gov.hmcts.reform.pip.channel.management.models.templatemodels;
Doesn't look like this class is used anywhere. Might have been superseded by SjpPressList. If so please remove it

2022-10-25 16:00 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        String html = artefact.getListType().getConverter().convert(topLevelNode, metadataMap, language);
From what I can see in data management, the PDF and excel got generated when we upload a json publication. So this is called every time. There are some lists without the converter and this is going to throw a null pointer exception here. We will need to check for that before calling the convert() method.

2022-10-25 16:06 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        publicationFilesMap.put(FileType.PDF, azureBlobService.getBlobFile(artefactId + ".pdf"));
For list types without PDF, what does azureBlobService.getBlobFile() returns? Is that null. I don't think we can insert null values to Java ConcurrentHashMap. This is going to generate an exception.

2022-10-25 16:08 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/datamanagement/ListType.java
> +    private Converter converter;
Now we have 2 converters. Might want to consider naming this to FileConverter

2022-10-25 16:11 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            byte[] outputExcel = artefact.getListType().getConverter().convertToExcel(topLevelNode);
Potential null pointer exception for list type without converter

2022-10-25 16:11 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            summary = artefact.getListType().getArtefactSummaryConverter().convert(rawJson);
Potential null pointer exception for list type without artefact summary exception

2022-10-25 16:16 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            if (outputPdf.length > 0 && outputPdf.length < 2_000_000) {
Can remember what was decided before. We only want to upload the file to Azure blob storage if less than 2MB? Thought it is more than 2MB.

2022-10-25 16:40 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            if (outputPdf.length > 0 && outputPdf.length < 2_000_000) {
The 2MB logic will remain in place until the 'ghost links' are done otherwise we will still get an issue when sending the file with notify. Upon the ghost link ticket being played this logic can be removed for SJP lists.

2022-10-25 16:43 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +        String html = artefact.getListType().getConverter().convert(topLevelNode, metadataMap, language);
There was logic in place to handle this when it was in publication services but it was agreed that it could be removed as the chance of this occurring is very low as the PDF/Excel will always be in place before a list is used in production.

2022-10-25 16:46 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            byte[] outputExcel = artefact.getListType().getConverter().convertToExcel(topLevelNode);
A list being used will always have a converter.

2022-10-25 16:46 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/PublicationManagementService.java
> +            summary = artefact.getListType().getArtefactSummaryConverter().convert(rawJson);
A list being used will always have a converter.

2022-10-25 16:48 UTC, ChrisS1512 requested changes

2022-10-25 19:26 UTC, joshblackmoor commented on src/main/resources/templates/testTemplate.html
> +<!DOCTYPE html>
Removed :)

2022-10-25 19:26 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/templatemodels/SjpPressCase.java
> +package uk.gov.hmcts.reform.pip.channel.management.models.templatemodels;
Yep, removed.

2022-10-25 19:26 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/models/external/datamanagement/ListType.java
> +    private Converter converter;
Renamed :)

2022-10-25 19:27 UTC, joshblackmoor commented on build.gradle
> +  implementation 'com.openhtmltopdf:openhtmltopdf-pdfbox:1.0.10'
Done :)

2022-10-26 12:33 UTC, KianKwa approved these changes

2022-11-01 14:50 UTC, ChrisS1512 approved these changes

2022-11-04 14:27 UTC, merged