PUB-1387 Magistrate Standard List Pdf Template
hmcts/pip-channel-management pull request #62
Opened 2022-11-10 14:14 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1387

### Change description ###

Pdf template for Magistrate Standard List.

![pdf-1](https://user-images.githubusercontent.com/84805836/201114536-f7437869-d55b-4489-93a6-5028063a68ee.jpg)

![pdf-2](https://user-images.githubusercontent.com/84805836/201114580-6f33bbc9-1de0-4b0b-9523-929bdb2278b4.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-11-11 11:34 UTC, ChrisS1512 requested changes

2022-11-11 11:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverter.java
> +                                hearing.get("offence").forEach(offence -> {
Offence can be optional therefore need a check here

2022-11-11 11:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverter.java
> +            + " " + hearing.get("gender").asText()
Gender and inCustody can be optional

2022-11-11 11:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/DateHelper.java
> +    public static void formatCaseTime(JsonNode sitting, String dateTimeNode, String destinationNode,
Is there any way this can be part of one of the existing methods above for time? I'm concious we have a lot of date / time methods in here which are similar, so would prefer not to add another if we can avoid!

2022-11-11 14:34 UTC, KianKwa approved these changes

2022-11-14 09:27 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverter.java
> +                                hearing.get("offence").forEach(offence -> {
it's fixed. I refactored the code.

2022-11-14 09:27 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverter.java
> +            + " " + hearing.get("gender").asText()
it's fixed. I refactored the code.

2022-11-14 09:38 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/filegeneration/helpers/DateHelper.java
> +    public static void formatCaseTime(JsonNode sitting, String dateTimeNode, String destinationNode,
Agree. No need to create this new function. removed it.

2022-11-14 10:30 UTC, ChrisS1512 approved these changes

2022-11-18 10:38 UTC, merged